
#we need to parametrise this
hardware_interface:
    loop_hz: 30
    joints:
    - front_right_wheel_joint
    - front_left_wheel_joint

generic_hw_control_loop:
    loop_hz: 50
    cycle_time_error_threshold: 0.01