rr_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

#we need to parametrise this
  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['front_left_wheel_joint']
    right_wheel: ['front_right_wheel_joint']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25
    open_loop: false
    # open_loop: true

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false


    # Base frame_id
    base_frame_id: base_link
    odom_frame_id: odom
    wheel_separation: 0.325
    wheel_radius: 0.095

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.04 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1   # m/s
        has_acceleration_limits: true
        max_acceleration       : 3.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 3   # rad/s^2