#Standard ROS diff drive controller
as_base_differential_controller:
  type: "diff_drive_controller/DiffDriveController"
  robot_description: /robot_description
  left_wheel: ["motor_wheel_joint_bl", "motor_wheel_joint_fl"]
  right_wheel: ["motor_wheel_joint_br", "motor_wheel_joint_fr"]
  publish_rate: 50

  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal:
    [0.01, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25
  open_loop: false
  # this is TF wheel odom only
  enable_odom_tf: true
  # Base frame_id
  base_frame_id: base_link
  odom_frame_id: odom

  wheel_separation: 0.54
  wheel_radius: 0.0762
  publish_cmd: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier: 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 0.8 # m/s
      has_acceleration_limits: true
      max_acceleration: 0.5 # m/s^2
      has_jerk_limits: false
      max_jerk: 0.1 # m/s^3
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2 # rad/s
      has_acceleration_limits: true
      max_acceleration: 1 # rad/s^2
      has_jerk_limits: false
      max_jerk: 0.4 # rad/s^3

  velocity_rolling_window_size: 10
  publish_wheel_joint_controller_state: true

as_base_holonomic_controller:
  type: mecanum_drive_controller/MecanumDriveController

  # Wheel parameters
  wheels:
    fl:
      name: motor_wheel_joint_fl
      x: 0.317 #0.72/2 - 0.043. 4 cm ish into the robot
      y: 0.2705 #0.455/2 + 0.043. 42-43 mm ish away from frame end.
    bl:
      name: motor_wheel_joint_bl
      x: -0.317
      y: 0.2705
    br:
      name: motor_wheel_joint_br
      x: -0.317
      y: -0.2705
    fr:
      name: motor_wheel_joint_fr
      x: 0.317
      y: -0.2705
    r: 0.107 #Simulation Rad:
    # r: 0.0762 #Real rad needs tuning

  # Odometry
  odom_frame_id: odom
  enable_odom_tf: false #Publishing to tf
  publish_rate: 50 #publish odometry
  pose_covariance_diagonal: [0.05, 0.05, 1000.0, 1000.0, 1000.0, 0.2]
  twist_covariance_diagonal: [0.02, 0.02, 1000.0, 1000.0, 1000.0, 0.05]

  # Misc
  cmd_vel_timeout: 0.1 #Velocity commands will be considered old if they are older than
  base_frame_id: base_link_footprint
  publish_cmd: true # Publish limited cmd

  # Limits:
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 0.8 # m/s
      has_acceleration_limits: true
      max_acceleration: 0.5 # m/s^2
      has_jerk_limits: false
      max_jerk: 0.1 # m/s^3
    y:
      has_velocity_limits: true
      max_velocity: 0.8 # m/s
      has_acceleration_limits: true
      max_acceleration: 0.5 # m/s^2
      has_jerk_limits: false
      max_jerk: 0.1 # m/s^3
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2 # rad/s
      has_acceleration_limits: true
      max_acceleration: 1 # rad/s^2
      has_jerk_limits: false
      max_jerk: 0.4 # rad/s^3

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
