topics:
-
  name    : mpc
  topic   : mpc_base_cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : joystick
  topic   : joy_base_cmd_vel
  timeout : 0.5
  priority: 100
locks:
-
  name    : pause
  topic   : pause_navigation
  timeout : 0.0
  # Same priority as joystick control, so it'll not block it.
  priority: 100
-
  name    : joystick 
  topic   : joy_priority
  timeout : 0.0
  priority: 100