# This file describes all controllers armstone would use in any case. Not all will be loaded. See control_manger spawner which is being loaded.

# joint_state_controller is actually an observer. i.e. publishes joint states... not confusing at all
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Individual wheell velocity controllers incase you wanna test something
joint_fl_motor_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor_wheel_joint_fl
    
joint_fr_motor_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor_wheel_joint_fr

joint_bl_motor_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor_wheel_joint_bl

joint_br_motor_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor_wheel_joint_br

#Multi vesc controller  i.e. set all joint velocities simultaniously
multi_vesc_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: 
      - motor_wheel_joint_fl
      - motor_wheel_joint_fr
      - motor_wheel_joint_bl
      - motor_wheel_joint_br

#Standard ROS diff drive controller
as_base_differential_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['motor_wheel_joint_bl', 'motor_wheel_joint_fl']
  right_wheel: ['motor_wheel_joint_br', 'motor_wheel_joint_fr']
  publish_rate: 50
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.01, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25
  open_loop: false        
  # this is TF wheel odom only
  enable_odom_tf: false
  # Base frame_id
  base_frame_id: base_link
  odom_frame_id: odom
  wheel_separation: 0.54
  wheel_radius: 0.0762

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.2   # m/s^2
      has_jerk_limits        : true
      max_jerk               : 0.1  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.8   # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 0.4  # rad/s^3

#Experimental ROS holonomic controller
as_base_mecanum_drive_controller:
  type: mecanum_drive_controller/MecanumDriveController
  use_realigned_roller_joints: false # Use the roller's radius rather than the wheel's:
  front_left_wheel_joint: motor_wheel_joint_fl
  back_left_wheel_joint: motor_wheel_joint_bl
  back_right_wheel_joint: motor_wheel_joint_br
  front_right_wheel_joint: motor_wheel_joint_fr
  enable_odom_tf: true #Publishing to tf 
  publish_rate: 50 #publish odometry
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  robot_description: robot_description
  cmd_vel_timeout: 0.1 #Velocity commands will be considered old if they are older than 
  base_frame_id: base_link
  base_frame_offset:
    x: 0.4 #TODO find meaning
    y: 0.25 #TODO find meaning
    theta: 1 #TODO find meaning
  