# Note all controllers at base level are named the same but will be loaded from different files. 
#Experimental ROS holonomic controller
as_base_controller:
  type: mecanum_drive_controller/MecanumDriveController
  use_realigned_roller_joints: false # Use the roller's radius rather than the wheel's:
  front_left_wheel_joint: motor_wheel_joint_fl
  back_left_wheel_joint: motor_wheel_joint_bl
  back_right_wheel_joint: motor_wheel_joint_br
  front_right_wheel_joint: motor_wheel_joint_fr
  enable_odom_tf: true #Publishing to tf 
  publish_rate: 50 #publish odometry
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  robot_description: /as_base/robot_description
  cmd_vel_timeout: 0.1 #Velocity commands will be considered old if they are older than 
  base_frame_id: base_link
  base_frame_offset:
    x: 0.4 #TODO find meaning
    y: 0.25 #TODO find meaning
    theta: 1 #TODO find meaning
  