# Note all controllers at base level are named the same but will be loaded from different files. 
#Standard ROS diff drive controller
as_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  robot_description: /as_control/robot_description
  left_wheel: ['motor_wheel_joint_bl', 'motor_wheel_joint_fl']
  right_wheel: ['motor_wheel_joint_br', 'motor_wheel_joint_fr']
  publish_rate: 50

  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.01, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25
  open_loop: false        
  # this is TF wheel odom only
  enable_odom_tf: true
  # Base frame_id
  base_frame_id: base_link
  odom_frame_id: odom

  wheel_separation: 0.54
  wheel_radius: 0.0762
  publish_cmd: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0 
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.8   # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.5   # m/s^2
      has_jerk_limits        : false
      max_jerk               : 0.1  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1   # rad/s^2
      has_jerk_limits        : false
      max_jerk               : 0.4  # rad/s^3

  velocity_rolling_window_size: 10
  publish_wheel_joint_controller_state: true
