joint_fl_motor_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor_wheel_joint_fl
    pid: {p: 1, i: 0, d: 0}

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


multi_vesc_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: 
      - motor_wheel_joint_fl
      - motor_wheel_joint_fr
      - motor_wheel_joint_bl
      - motor_wheel_joint_br
  gains:
      motor_wheel_joint_fl: {p: 1, i: 1, d: 0}
      motor_wheel_joint_fr: {p: 1, i: 1, d: 0}
      motor_wheel_joint_bl: {p: 1, i: 1, d: 0}
      motor_wheel_joint_br: {p: 1, i: 1, d: 0}

# as_base_controller:
#   type: "diff_drive_controller/DiffDriveController"
#   left_wheel: ['motor_wheel_joint_bl', 'motor_wheel_joint_fl']
#   right_wheel: ['motor_wheel_joint_br', 'motor_wheel_joint_fr']
#   publish_rate: 50
#   pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
#   twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
#   cmd_vel_timeout: 0.25
#   open_loop: false        
#   # this is TF wheel odom only
#   enable_odom_tf: false
#   # Base frame_id
#   base_frame_id: base_link
#   odom_frame_id: odom
#   wheel_separation: 0.54
#   wheel_radius: 0.0762

#   # Wheel separation and radius multipliers
#   wheel_separation_multiplier: 1.0 # default: 1.0
#   wheel_radius_multiplier    : 1.0 # default: 1.0

#   # Velocity and acceleration limits
#   # Whenever a min_* is unspecified, default to -max_*
#   linear:
#     x:
#       has_velocity_limits    : true
#       max_velocity           : 0.5   # m/s
#       has_acceleration_limits: true
#       max_acceleration       : 0.5   # m/s^2
#       has_jerk_limits        : true
#       max_jerk               : 1.0  # m/s^3
#   angular:
#     z:
#       has_velocity_limits    : true
#       max_velocity           : 1.5   # rad/s
#       has_acceleration_limits: true
#       max_acceleration       : 1   # rad/s^2
#       has_jerk_limits        : true
#       max_jerk               : 2  # rad/s^3

# multi_vesc_controller:
#   type: velocity_controllers/JointGroupVelocityController
#   joints: 
#       - motor_wheel_joint_fl
#       - motor_wheel_joint_fr
#       - motor_wheel_joint_bl
#       - motor_wheel_joint_br
#   gains:
#       joint_front_right_prop: {p: 10000, i: 1, d: 1000}
#       joint_front_left_prop: {p: 10000, i: 1, d: 1000}
#       joint_back_left_prop: {p: 10000, i: 1, d: 1000}
#       joint_back_right_prop: {p: 10000, i: 1, d: 1000}