axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.2
  y: 0.2
scale_linear_turbo:
  x: 0.5
  y: 0.5
axis_angular:
  yaw: 3
scale_angular:
  yaw: 0.5
scale_angular_turbo:
  yaw: 0.3
enable_button: 5
enable_turbo_button: 1