<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- Link Dimensions -->
	<!-- base_link -->
	<xacro:property name="base_link_dx" value="0.72"/>
	<xacro:property name="base_link_dy" value="0.455"/>
	<xacro:property name="base_link_dz" value="0.15"/>
	<!-- 2.8kg raw frame. 3.5 estimate  full -->
	<xacro:property name="base_link_m" value="3.5"/>
	<!-- alluminium frame only -->

	<!-- wheel_link -->
	<xacro:property name="wheel_link_r" value="${0.152/2}"/>
	<xacro:property name="wheel_link_m" value="0.6"/>
	<xacro:property name="wheel_roller_angle" value="${45*M_PI/180}"/>

	<!-- motor_gearbox_link -->
	<xacro:property name="motor_link_r" value="0.025"/>
	<!-- motor normal 12 cm. But with coupler +5cm -->
	<xacro:property name="motor_link_h" value="${0.12+0.05}"/>
	<xacro:property name="motor_link_m" value="${0.14 +0.36}"/>
	<!-- True is 1460mNm -->
	<xacro:property name="motor_effort_limit" value="1.4"/>
	<!-- True is 6110rpm -->
	<xacro:property name="motor_velocity_limit" value="600"/>
	<xacro:property name="gearbox_reduction" value="91"/>

	<!-- offsets -->
	<xacro:property name="motor_wheel_assemply_xyz_fl" value="${base_link_dx/2-0.05} ${base_link_dy/2 -motor_link_h/2} -${base_link_dz/2 + motor_link_r/2}"/>
	<xacro:property name="motor_wheel_assemply_rpy_fl" value="${- M_PI/2} 0 0"/>
	<xacro:property name="motor_wheel_assemply_xyz_fr" value="${base_link_dx/2-0.05} -${base_link_dy/2 -motor_link_h/2} -${base_link_dz/2 + motor_link_r/2}"/>
	<xacro:property name="motor_wheel_assemply_rpy_fr" value="${M_PI/2} 0 0"/>
	<xacro:property name="motor_wheel_assemply_xyz_bl" value="-${base_link_dx/2-0.05} ${base_link_dy/2 -motor_link_h/2} -${base_link_dz/2 + motor_link_r/2}"/>
	<xacro:property name="motor_wheel_assemply_rpy_bl" value="${ M_PI/2} 0 ${M_PI}"/>
	<xacro:property name="motor_wheel_assemply_xyz_br" value="-${base_link_dx/2-0.05} -${base_link_dy/2 -motor_link_h/2} -${base_link_dz/2 + motor_link_r/2}"/>
	<xacro:property name="motor_wheel_assemply_rpy_br" value="${-M_PI/2} 0 ${M_PI}"/>

	<xacro:property name="ground_clearance" value="${motor_link_r/2 +wheel_link_r/2}"/>

	<!-- Import Things -->
	<xacro:include filename="$(find as_description)/urdf/base/chasis.xacro"/>
	<xacro:include filename="$(find as_description)/urdf/components/components.xacro"/>

	<!-- Componenet positions-->
	<xacro:property name="battery_xyz" value="-${base_link_dx/2 - 0.18} 0 -${base_link_dz/2 - 0.01 - battery_link_dz/2}"/>
	<xacro:property name="battery_rpy" value=" 0 0 ${M_PI/2}"/>

	<xacro:property name="nuc_xyz" value="-${nuc_link_dz/2} ${base_link_dy/4} 0"/>
	<xacro:property name="nuc_rpy" value=" 0 ${M_PI/2} 0"/>

	<xacro:property name="dc_box_xyz" value=" 0.05 0 -${base_link_dz/2-0.01 - dc_box_dz/2}"/>
	<xacro:property name="dc_box_rpy" value=" 0 0 0"/>

	<xacro:property name="material3_xyz" value="-${base_link_dx/4} 0 ${base_link_dz/2+0.01 + battery_link_dz/2}"/>
	<xacro:property name="material3_rpy" value="0 ${M_PI/2} 0"/>

	<xacro:property name="mount_plate_xyz" value=" ${base_link_dx/2 - mount_plate_dx/2} 0 -${ base_link_dz/2 -mount_plate_dz/2 -0.01}"/>
	<xacro:property name="mount_plate_rpy" value="0 0 0"/>

	<xacro:property name="compressor_xyz" value="-${base_link_dx/2-compressor_h/2 } ${base_link_dy/2 - compressor_r/2} ${base_link_dz/2-compressor_r }"/>
	<xacro:property name="compressor_rpy" value="0 ${M_PI/2} 0"/>

	<!-- Actual Things -->
	<xacro:as_base/>
	<xacro:battery48 parent="base_link" xyz="${battery_xyz}" rpy="${battery_rpy}" />
	<xacro:nuc parent="base_link" xyz="${nuc_xyz}" rpy="${nuc_rpy}" />
	<xacro:dc_box parent="base_link" xyz="${dc_box_xyz}" rpy="${dc_box_rpy}" />
	<xacro:mount_plate parent="base_link" xyz="${mount_plate_xyz}" rpy="${mount_plate_rpy}" />
	<xacro:compressor parent="base_link" xyz="${compressor_xyz}" rpy="${compressor_rpy}" />
	<xacro:material3 parent="base_link" xyz="${material3_xyz}" rpy="${material3_rpy}" />

</robot>
