<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:xacro="http://ros.org/wiki/xacro">



	<!-- Common -->
	<xacro:include filename="$(find as_description)/urdf/common/inertia.xacro"/>
	<xacro:include filename="$(find as_description)/urdf/common/materials.xacro"/>

	<xacro:macro name="as_motor_wheel_assembly" params="suffix wheel_angle  " >

		<link name="motor_gearbox${suffix}">
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${motor_link_m}"/>
				<xacro:cylinder_inertia_tensor m="${motor_link_m}" r="${motor_link_r}" h="${motor_link_h}" />
			</inertial>
			<visual>
				<origin xyz= "${motor_mxyz}" rpy = "${motor_mrpy}" />
				<geometry>										
					<mesh filename="package://as_description/meshes/${motor_meshfile}" />
				</geometry>				
			</visual>
			<collision>
				<geometry>
					<cylinder length="${motor_link_h}" radius="${motor_link_r}"/>
				</geometry>
			</collision>
		</link>

		<joint name="motor_wheel_joint${suffix}" type="continuous">
			<parent link="motor_gearbox${suffix}"/>
			<child link="omniwheel${suffix}"/>
			<origin xyz= "0 0 ${motor_link_h/2}" rpy = "0 ${wheel_angle} 0" />
			<axis xyz="0 0 1"/>
			<limit effort = "${motor_effort_limit}" velocity = "${motor_velocity_limit}" />
			<dynamics damping="1.5" friction="1.0"/>
		</joint>

		<transmission name="motor_wheel_joint_transmission${suffix}">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="motor_wheel_joint${suffix}">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			</joint>
			<actuator name="motor_wheel_joint_actuator${suffix}">
				<mechanicalReduction>${gearbox_reduction}</mechanicalReduction>
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
			</actuator>
		</transmission>


		<link name="omniwheel${suffix}">
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${wheel_link_m}"/>
				<xacro:sphere_inertia_tensor m="${wheel_link_m}" r="${wheel_link_r/2}" />
			</inertial>
			<!-- No visual. -->
			<collision>
				<geometry>
					<sphere radius="${wheel_link_r}"/>
				</geometry>
			</collision>

			<visual>
				<!-- dummy visual so gazebo doesnt freakout -->
				<geometry>
					<sphere radius="${wheel_link_r/10}"/>
				</geometry>
			</visual>

		</link>

		<gazebo reference="omniwheel${suffix}">
			<mu1 value="0.2"/>
			<mu2 value="1.5"/>
			<kp value="10000000.0" />
			<kd value="10000.0" />
			<fdir1 value="0 0 1"/>
			<maxContacts value= "1"/>
			<material>Gazebo/White</material>
		</gazebo>

	</xacro:macro>


	<xacro:macro name="as_base_chasis">

		<!-- Projection of base_link origin to xy plane -->
		<link name="base_link_footprint"/>
		<joint name="joint0" type="fixed">
			<parent link="base_link_footprint"/>
			<child link="base_link_base"/>
			<origin xyz= "0 0 ${ground_clearance}" rpy = "0 0 0" />
		</joint>
		<!-- Projection of base_link origin to bottom of baselink collision box (i.e. raised only by wheels) -->
		<link name="base_link_base"/>
		<joint name="joint1" type="fixed">
			<parent link="base_link_base"/>
			<child link="base_link"/>
			<origin xyz= "0 0 ${base_link_dz/2}" rpy = "0 0 0" />
		</joint>
		<!-- baselink -->
		<link name="base_link">
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${base_link_m}"/>
				<xacro:box_inertia_tensor m="${base_link_m}" dx="${base_link_dx}" dy="${base_link_dy}" dz="${base_link_dz}"/>
			</inertial>
			<visual>				
				<origin xyz= "${base_mxyz}" rpy = "${base_mrpy}" />
				<geometry>										
					<mesh filename="package://as_description/meshes/${base_meshfile}" />
				</geometry>				
			</visual>
			<collision>
				<geometry>
					<box size="${base_link_dx} ${base_link_dy} ${base_link_dz}" />
				</geometry>
			</collision>

			<gazebo reference="base_link">
				<material>Gazebo/DarkGrey</material>
			</gazebo>
		</link>

		<xacro:as_motor_wheel_assembly suffix="_fl"  wheel_angle="${-wheel_roller_angle}"/>
		<xacro:as_motor_wheel_assembly suffix="_fr"  wheel_angle="${wheel_roller_angle}"/>
		<xacro:as_motor_wheel_assembly suffix="_bl"  wheel_angle="${wheel_roller_angle}"/>
		<xacro:as_motor_wheel_assembly suffix="_br"  wheel_angle="${-wheel_roller_angle}"/>

		<joint name="motor_wheel_assembly_joint_fl" type="fixed">
			<parent link="base_link"/>
			<child link="motor_gearbox_fl"/>
			<origin xyz= "${motor_wheel_assembly_xyz_fl}" rpy = "${motor_wheel_assembly_rpy_fl}" />
		</joint>

		<joint name="motor_wheel_assembly_joint_fr" type="fixed">
			<parent link="base_link"/>
			<child link="motor_gearbox_fr"/>
			<origin xyz= "${motor_wheel_assembly_xyz_fr}" rpy = "${motor_wheel_assembly_rpy_fr}" />
		</joint>

		<joint name="motor_wheel_assembly_joint_bl" type="fixed">
			<parent link="base_link"/>
			<child link="motor_gearbox_bl"/>
			<origin xyz= "${motor_wheel_assembly_xyz_bl}" rpy = "${motor_wheel_assembly_rpy_bl}" />
		</joint>

		<joint name="motor_wheel_assembly_joint_br" type="fixed">
			<parent link="base_link"/>
			<child link="motor_gearbox_br"/>
			<origin xyz= "${motor_wheel_assembly_xyz_br}" rpy = "${motor_wheel_assembly_rpy_br}" />
		</joint>

		
	</xacro:macro>




</robot>
