<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find as_description)/urdf/common/generic_links.xacro"/>
	<xacro:include filename="$(find sensor_imu)/urdf/sensor_imu.xacro"/>

	<!-- battery_link -->
	<xacro:property name="battery_link_dx" value="0.40"/>
	<xacro:property name="battery_link_dy" value="0.150"/>
	<xacro:property name="battery_link_dz" value="0.085"/>
	<xacro:property name="battery_link_m" value="6.7"/>

	<!-- nuc_link -->
	<xacro:property name="nuc_link_dx" value="0.12"/>
	<xacro:property name="nuc_link_dy" value="0.12"/>
	<xacro:property name="nuc_link_dz" value="0.06"/>
	<xacro:property name="nuc_link_m" value="0.3"/>

	<!-- DC Control box -->
	<xacro:property name="dc_box_dx" value="0.18"/>
	<xacro:property name="dc_box_dy" value="0.145"/>
	<xacro:property name="dc_box_dz" value="0.068"/>
	<xacro:property name="dc_box_m" value="1.8"/>

	<!-- Material Cylinder 3 -->
	<xacro:property name="material3_r" value="0.0525"/>
	<xacro:property name="material3_h" value="0.42"/>
	<xacro:property name="material3_m" value="${3*1760/1000}"/>

	<!-- Aluminium plate -->
	<xacro:property name="mount_plate_dx" value="${0.27}"/>
	<xacro:property name="mount_plate_dy" value="${0.455}"/>
	<xacro:property name="mount_plate_dz" value="0.008"/>
	<!-- Aluminium density 2.7/cm3  or 2700 kgm3-->
	<!-- About 3.5 kg aluminium plate. -->
	<xacro:property name="mount_plate_m" value="${2700*mount_plate_dx*mount_plate_dy*mount_plate_dz}"/>

	<!-- Extruder -->
	<xacro:property name="extruder_r" value="0.05"/>
    <xacro:property name="extruder_h" value="0.17"/>
    <!--Without material m 1.05 (including bolts)  -->
	<!--with tube maybe more-->
    <xacro:property name="extruder_m" value="1.05"/>

	<xacro:property name="ee_imu_xyz" value="0 -${(0.035 +(0.0525/2))} 0"/>
	<xacro:property name="ee_imu_rpy" value="0 3.14159265359 0"/>

	

	<xacro:macro name="battery48" params="parent xyz rpy">
		<xacro:generic_box name="battery48" parent="${parent}" xyz="${xyz}" rpy="${rpy}" dx="${battery_link_dx}" dy="${battery_link_dy}" dz="${battery_link_dz}" m="${battery_link_m}" material="LightGrey" gmaterial="Gazebo/LightGrey" meshfile="battery.dae" mxyz="0.035 0 ${-battery_link_dz/2}" mrpy="0 0 ${M_PI}" />
	</xacro:macro>

	<xacro:macro name="nuc" params="parent xyz rpy suffix">
		<xacro:generic_box name="nuc${suffix}" parent="${parent}" xyz="${xyz}" rpy="${rpy}" dx="${nuc_link_dx}" dy="${nuc_link_dy}" dz="${nuc_link_dz}" m="${nuc_link_m}" material="DarkGrey" gmaterial="Gazebo/DarkGrey" meshfile="nuc.stl" mxyz="0 0 0" mrpy="0 0 0" />
	</xacro:macro>

	<xacro:macro name="dc_box" params="parent xyz rpy">
		<xacro:generic_box name="dc_box" parent="${parent}" xyz="${xyz}" rpy="${rpy}" dx="${dc_box_dx}" dy="${dc_box_dy}" dz="${dc_box_dz}" m="${dc_box_m}" material="LightGrey" gmaterial="Gazebo/LightGrey" meshfile="dcbox.dae" mxyz="0 0 ${dc_box_dz/2}" mrpy="0 0 ${M_PI/2} " />
	</xacro:macro>

	<xacro:macro name="mount_plate" params="parent xyz rpy">
		<xacro:generic_box name="mount_plate" parent="${parent}" xyz="${xyz}" rpy="${rpy}" dx="${mount_plate_dx}" dy="${mount_plate_dy}" dz="${mount_plate_dz}" m="${mount_plate_m}" material="LightGrey" gmaterial="Gazebo/LightGrey" meshfile="mounting_plate.stl" mxyz="0 0 ${-mount_plate_dz/2}" mrpy="0 0 ${M_PI/2}" />
	</xacro:macro>

	<xacro:macro name="compressor" params="parent xyz rpy">
		<xacro:generic_box name="compressor" parent="${parent}" xyz="${xyz}" rpy="${rpy}" dx="${compressor_box_dx}" dy="${compressor_box_dy}" dz="${compressor_box_dz}" m="${compressor_m}" material="Grey" gmaterial="Gazebo/Grey" meshfile="compressor_assembly.dae" mxyz="0 0 ${-compressor_box_dz/2}" mrpy="0 0 0" />
	</xacro:macro>

	<xacro:macro name="material3" params="parent xyz rpy">
		<xacro:generic_cylinder name="material3" parent="${parent}" xyz="${xyz}" rpy="${rpy}" r="${material3_r}" h="${material3_h}" m="${material3_m}" material="LightGrey" gmaterial="Gazebo/LightGrey" meshfile="clay_assembly.dae" mxyz="${material3_r+0.02}  0  ${material3_h/5}" mrpy="0 ${-M_PI/2} 0"/>
	</xacro:macro>

	<xacro:macro name="cover_plate" params="parent xyz rpy">
		<xacro:generic_box name="cover_plate" parent="${parent}" xyz="${xyz}" rpy="${rpy}" dx="${cover_box_dx}" dy="${cover_box_dy}" dz="${cover_box_dz}" m="${cover_plate_m}" material="LightGrey" gmaterial="Gazebo/LightGrey" meshfile="cover_assembly_.dae" mxyz="0 0 0" mrpy="0 0 0"/>
	</xacro:macro>

	<xacro:macro name="ic" params="parent xyz rpy">
		<xacro:generic_box name="ic" parent="${parent}" xyz="${xyz}" rpy="${rpy}" dx="${ic_box_dx}" dy="${ic_box_dy}" dz="${ic_box_dz}" m="${ic_m}" material="LightGrey" gmaterial="Gazebo/LightGrey" meshfile="intermediate_assembly.dae" mxyz="${ic_box_dx/2 - 0.03} 0 ${-ic_box_dz/2}" mrpy="0 0 0"/>
	</xacro:macro>

	<xacro:macro name="extruder" params="parent xyz rpy">	
		
		<joint name="extruder_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="extruder_link"/>
            <origin xyz= "${xyz}" rpy = "${rpy}" />
        </joint>

        <link name="extruder_link">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${extruder_m}"/>
                <xacro:cylinder_inertia_tensor m="${extruder_m}" r="${extruder_r}" h="${extruder_h}"/>
            </inertial>
            <visual>               
				<origin xyz= "0 0 ${-extruder_h/2}" rpy = "0 0 0" />
				<geometry>                        
					<mesh filename="package://as_description/meshes/extruder.dae" />
				</geometry>                              
            </visual>
            <collision>				
                <origin xyz= "0 0 ${-extruder_h/2}" rpy = "0 0 0" />
				<geometry>                        
					<mesh filename="package://as_description/meshes/extruder_collision.dae" />
				</geometry>              
            </collision>		
        </link>  

		<link name="extruder_ee"/>
		<joint name="extruder_ee_joint" type="fixed">
			  <parent link="extruder_link"/>
			  <child link="extruder_ee"/>
			  <origin xyz= "0 0 ${extruder_h/2}" rpy = "0 0 0" />
		</joint>		
		<xacro:imu prefix="ee" parent="${parent}" xyz="${ee_imu_xyz}" rpy="${ee_imu_rpy}" />
		
	</xacro:macro>

	<xacro:macro name="backpack" params="parent xyz rpy">	
		
		<joint name="backpack_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="backpack_link"/>
            <origin xyz= "${xyz}" rpy = "${rpy}" />
        </joint>

        <link name="backpack_link"> 
			<collision>
                <geometry>
                    <box size="${backpack_dx} ${backpack_dy} ${backpack_dz}" />
                </geometry>
            </collision>		
        </link>  
	</xacro:macro>

</robot>
